### ISSUE TITLE
the error of train

### ISSUE THREAD

**Issue by zyuxiang0822** [lpcccc-cv/MC-CDic#11]
You're doing a fantastic job. I've tried running the code but encountered some issues. I hope to get a response from you.
23-10-30 16:56:17.028 - INFO: Model [BaseModel] is created.
23-10-30 16:56:17.028 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 162, in main
    model.optimize_parameters()
  File "/home/MC-CDic-main/models/ref_rec_base_model.py", line 147, in optimize_parameters
    self.fake_2 = self.netG(self.im2_lr, self.im1_gt, self.mask)
  File "/home/zhongyuxiang/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by lpcccc-cv** [comment]
You can remove the "self.mask" in line 147.
Modify 
self.fake_2 = self.netG(self.im2_lr, self.im1_gt, self.mask)
to
self.fake_2 = self.netG(self.im2_lr, self.im1_gt)

**Comment by zyuxiang0822** [comment]
Thank you very much!
