### ISSUE TITLE
about data size and mask size

### ISSUE THREAD

**Issue by iaOlivia** [lpcccc-cv/MC-CDic#7]
I notice data was crop to (128,128) but mask's shape is (256,256) .It seems to lead to an error.please see below code.
 if self.train:
            _, H, W = im1_GT.shape 
            if self.hr_in:
                rnd_h = random.randint(0, max(0, H - self.crop_size))
                rnd_w = random.randint(0, max(0, W - self.crop_size))
                im1_GT = im1_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_GT = im2_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
            else:
                rnd_h = random.randint(0, max(0, H//self.scale - self.crop_size))
                rnd_w = random.randint(0, max(0, W//self.scale - self.crop_size))
                rnd_h_HR, rnd_w_HR = int(rnd_h * self.scale), int(rnd_w * self.scale)
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_GT = im1_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
                im2_GT = im2_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
            print('12 12 12',im2_LQ.shape)
                
        print('101010',im1_GT.shape)
        return {'im1_LQ':im1_LQ, 'im1_GT':im1_GT, 'im2_LQ':im2_LQ, 'im2_GT':im2_GT, 'mask':mask}

**Comment by iaOlivia** [comment]
I try to add below two bold sentence to keep shape same.It seems reasonable for me and nort raise error.How do you think?
           if self.hr_in:
                rnd_h = random.randint(0, max(0, H - self.crop_size))
                rnd_w = random.randint(0, max(0, W - self.crop_size))
                im1_GT = im1_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_GT = im2_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                **mask   = mask[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]**
            else:
                rnd_h = random.randint(0, max(0, H//self.scale - self.crop_size))
                rnd_w = random.randint(0, max(0, W//self.scale - self.crop_size))
                rnd_h_HR, rnd_w_HR = int(rnd_h * self.scale), int(rnd_w * self.scale)
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_GT = im1_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
                im2_GT = im2_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
                **mask = mask[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]**

**Comment by lpcccc-cv** [comment]
No, you can not crop the mask! You should crop the under-sampled image. Our MC-CDic model was implemented on image domain, the shape of the mask (256x256) would not affect the model with 128*128 images.

**Comment by iaOlivia** [comment]
yeah, I see . but code run here when train and it will crop the image from (256,256) to (128,128) then raise shape error.Or should set  self.hr_in =False to keep image size?
        if self.train:
            _, H, W = im1_GT.shape 
            if self.hr_in:
                rnd_h = random.randint(0, max(0, H - self.crop_size))
                rnd_w = random.randint(0, max(0, W - self.crop_size))
                im1_GT = im1_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_GT = im2_GT[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                mask   = mask[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
            else:
                rnd_h = random.randint(0, max(0, H//self.scale - self.crop_size))
                rnd_w = random.randint(0, max(0, W//self.scale - self.crop_size))
                rnd_h_HR, rnd_w_HR = int(rnd_h * self.scale), int(rnd_w * self.scale)
                im1_LQ = im1_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im2_LQ = im2_LQ[:, rnd_h:rnd_h + self.crop_size, rnd_w:rnd_w + self.crop_size]
                im1_GT = im1_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
                im2_GT = im2_GT[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]
                mask = mask[:, rnd_h_HR:rnd_h_HR + self.crop_size*self.scale, rnd_w_HR:rnd_w_HR + self.crop_size*self.scale]

**Comment by lpcccc-cv** [comment]
No, the self.hr_in should be set True. It just a cropping operation, I don't know why it raise this error. Is the shape of image GT and LQ are 256*256? Can you show the detailed errors to me?

**Comment by iaOlivia** [comment]
as below:
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 163, in main
    model.optimize_parameters()
  File "/home/ac/data/wyl/projects/MC-CDic-main/models/ref_rec_base_model.py", line 152, in optimize_parameters
    l_kspace = self.fft_loss(self.fake_2, self.im2_gt, self.mask) * 0.0001
  File "/home/ac/anaconda3/envs/mc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ac/data/wyl/projects/MC-CDic-main/models/modules/loss.py", line 29, in forward
    **loss = torch.mean(abs(diff*mask))**
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 3

**Comment by iaOlivia** [comment]
diff shape is (128,128) but mask shape is (256,256)

**Comment by lpcccc-cv** [comment]
I know. You should comment out the K-space loss. 
"l_kspace = self.fft_loss(self.fake_2, self.im2_gt, self.mask) * 0.0001"

**Comment by iaOlivia** [comment]
if so ,we can't caculate the l_kspace?

**Comment by lpcccc-cv** [comment]
It seems so. If you want use the k-space loss, you should keep the original size as model input.

**Comment by iaOlivia** [comment]
alright.I see.I will try to figure it out.

**Comment by iaOlivia** [comment]
Thank you.

**Comment by iaOlivia** [comment]
Hi,
I see in modelx4.yml file that default crop_size of train datastes is set to 128 as below:
datasets:
  train:
    mode: IXI
    task: rec       # sr / rec
    scale: 4
    interval_list: [1]
    random_reverse: true
    border_mode: false
#    dataroot_GT: /home/lpc/dataset/IXI/MC_MRI/T2
    dataroot_GT: /home/ac/data/wyl/projects/savepng/T2
    # dataroot_GT: /home/lpc/dataset/BrainTS/MCSR/T1_train
    use_shuffle: true
    n_workers: 2
    batch_size: 1
    **crop_size: 128**
    use_flip: True
    use_rot: True
    hr_in: True
 
class IXI_train(data.Dataset):
    def __init__(self, opt, train):
        super(IXI_train, self).__init__()
        path = opt['dataroot_GT']
        GT_list = sorted(os.listdir(path))
        self.GT_paths = [os.path.join(path, i) for i in GT_list]
        self.train = train
        **if self.train:
            self.crop_size = opt['crop_size']**
        else:
            self.crop_size = opt['test_size']
        self.task = opt['task']
        self.scale = int(opt['scale'])
        self.hr_in = opt['hr_in']

It seems conflict with demand to keep image domain?

**Comment by lpcccc-cv** [comment]
Sorry, I don't understand what you mean.

**Comment by iaOlivia** [comment]
I mean even if original image size is (256,256) but it will be crop to crop_size which id defined in .yml file ,i see defualt value is 128.

**Comment by lpcccc-cv** [comment]
Of course, if you don't want to crop the  image, you can set crop_size=256.

**Comment by iaOlivia** [comment]
maybe this is reason that cause l_kspace problem
